language: julia

os:
  - linux

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("RDates"; coverage=true)'

after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'

  # Submit the test coverage report
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'
  #Buidl and deploy documentation
  - julia --project ./docs/make.jl
